### ISSUE TITLE
abstract features as mode transition triggers

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#671]
**Issue**: currently limited to ports. Should allow abstract feature as well.
**Proposed change**: Change to abstract feature.

**Status **Approved 2/14. Documented. To Be Implemented

**Comment by lwrage** [comment]
It's not quite clear what we should implement. The proposed change allows abstract features only, so ports would no longer be allowed. The draft standard has a change from ports to all features, which is also problematic because that includes access features.
BTW, the semantics section only mentions event ports and event data ports.
The metamodel currently allows abstract features and ports.

**Comment by reteprelief** [comment]
The issue is that several port types can trigger the mode transition. Early in the design users may not yet have decided whether it is going to be an event port or event data port. Since we do not have a generic port declaration the user will have to use the abstract feature declaration.
In this setting we will need a legality rule that the abstract feature can only be refined to one of those two port types.

**Comment by lwrage** [comment]
See saeaadl/aadlv2.1#10
