### ISSUE TITLE
Actual_Connection_Binding for connecton array

### ISSUE THREAD

**Issue by juli1** [osate/osate2-core#751]
Hi,

See https://gist.github.com/juli1/117c4916ef2547061595ff50d8008d41
When instantiating the model, there is an error related to the Connection Binding property on the connection. The same object is being referenced multiple times. It triggers an error in the instance model.

**Comment by lwrage** [comment]
Could you explain what "the same object is referenced multiple times" means, please? Which object, referenced where?

**Comment by juli1** [comment]
Well, when instantiating, I got the following message: "Reference refers to more than one instance object"
Try to instantiate the model from the gist to reproduce the bug. Long story short, the problem is when the connection is bound to an array of components. Not sure if the language handles this - it might be finally a language issue.

**Comment by lwrage** [comment]
I think the intention of the model is that each connection is bound to a different bus. This is not possible in AADL because we can't reference an individual connection between array elements.
The error message is fine because we have a limitation in OSATE. According to the standard we'd need to automatically create a list of reference values in this case. This is not implemented (implementing it would likely require significant effort).
