### ISSUE TITLE
Renaming an element causes format loss

### ISSUE THREAD

**Issue by lwrage** [osate/osate2-core#828]
If an element is renamed in its textual form (AADL) then formatting is lost in its associated graphical view.

**Comment by philip-alldredge** [comment]
Closing this. I have just merged a substantial rework to the graphical editor which should fix the issue with a caveat: If the user just renames an element in the text editor then the formatting will be lost. However, if the user performs a rename refactoring on an element, then affected references which are contained in diagrams should be updated.

The graphical editor now uses LTK refactoring to perform renames so that should help flush out any cases that haven't been handled. While testing things, I found a few cases where refactoring from the text editor can produce errors in the model. I'll go over my notes and report those as separate issue(s) sometime next week.
